<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-EVOAUGI" failures="2" tests="4" name="Listener Test" time="5.456" errors="0" timestamp="2022-11-07T23:52:54 EST">
  <testcase classname="ui.Testng.ScreenShotForFailedTestCases" name="test0" time="0.011"/>
  <testcase classname="ui.Testng.ScreenShotForFailedTestCases" name="test1" time="4.091">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at ui.Testng.ScreenShotForFailedTestCases.test1(ScreenShotForFailedTestCases.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="ui.Testng.ScreenShotForFailedTestCases" name="test2" time="1.013">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method ui.Testng.ScreenShotForFailedTestCases.test2() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method ui.Testng.ScreenShotForFailedTestCases.test2() didn't finish within the time-out 1000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="ui.Testng.ScreenShotForFailedTestCases" name="standby" time="0.0">
    <skipped/>
  </testcase> <!-- standby -->
</testsuite> <!-- Listener Test -->
